### ISSUE TITLE
Phishing Detection Benchmark

### ISSUE THREAD

**Issue by Fujiaoji** [code-philia/PhishLLM#10]
Hi Ruofan,

Thanks for sharing the project. I am wondering that the dataset for Phishing Detection Benchmark contains 6K (6,075) phishing websites + 6K (6,075) benign websites. It looks like you have not shared the benign one. Will you publish it? Thanks
Have a great day.

**Comment by lindsey98** [comment]
Hi Fujiao, 
  Somehow I cannot find the benign website data. 
  But I still keep their links, please see the the first column in the attached txt.
[alexa7k_phishintention.txt](https://github.com/user-attachments/files/17376512/alexa7k_phishintention.txt)

**Comment by Fujiaoji** [comment]
> Hi Fujiao, Somehow I cannot find the benign website data. But I still keep their links, please see the the first column in the attached txt. [alexa7k_phishintention.txt](https://github.com/user-attachments/files/17376512/alexa7k_phishintention.txt)

Thanks for your quick reply. It helps a lot.
